In [4]:
import numpy as np

 Q1 — Building the class register

In [ ]:
s1 = [72,85,60,91]
s2 = [45,30,98,55]
s3 = [88,66,74,100]
old = np.array([['62','71','55','80'], 
                ['49','58','66','73']])
table = np.vstack([s1,s2,s3])         #1
print(table)


students = table.shape[0]             #2
subjects = table.shape[1]            

total = table.size                    #3


table2 = table.copy().astype('float')    #4


old_int = old.astype('int')             #5
total_oldint = old_int.sum(axis=1)


table_final = np.vstack([table,old_int])     #6
print(students)
print(subjects)
print(total)
print(table2)
print(old_int)
print(total_oldint)
print(table_final)

3 4
12
[268 246]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


Q2 — Templates and sequences


In [ ]:
marks = np.zeros((6,4))         #1


table = np.full((6,4),35)       #2

roll_nos = np.arange(101,130,2)     #3



timetable = np.linspace(0,3,7)        #4

table2 = np.eye(5)                  #5
np.fill_diagonal(table2,10)


table3 = np.full((4,4),35)          #6
np.fill_diagonal(table3,100)


print(marks)
print(table)
print(roll_nos.size)
print(timetable)
print(table2)
print(table3)

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129] 15
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


Q3. The attendance row

In [ ]:
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])
 
print(present[0], present[-1])                          
print(present[1::2])                                    
print(present[-4:])                                      
reversed_row = present[::-1]                             
print(reversed_row[::3])                                 
present[4:6] = 30                                         
half = len(present) // 2                                  
print(present[:half] - present[half:])                     
print(present[::-1][:3])                                   




 #ALTERNATE


#present = np.array([22,18,25,12,20,24,9,21,17,23])


#print(present[0])             #1
#print(present[-1]) 


#print(present[1::2])        #2


#print(present[6::])       #3


#reverse=present[::-1]       #4
#print(reverse[::3])


#first_half = present[0:5]             #6
#second_half = present[5:10]
#print(first_half-second_half)


#present[4:6] = 30        #5


#reversed_row = present[::-1]                  #7
#top_three = np.sort(reversed_row)[-3:]
#print(top_three)

22 23
[18 12 24 21 23]
[ 9 21 17 23]
[23  9 12 22]
[-8  9  4 -5  7]
[23 17 21]


Q4 — Reading the mark sheet

In [ ]:
marks = np.array([[72, 85, 60, 91],
                   [45, 30, 98, 55],
                   [88, 66, 74, 100],
                   [95, 92, 55, 40],
                   [30, 48, 62, 70]])
 
print(marks[1:4, 1:3])                                    
print(marks[:, -1])                                      
print(marks[:, [0, -1]])                                  
print(marks[::-1])                                       
marks[:, 2] += 5                                          
print(marks[-1, -2])                                       
print(marks[-2:, :2])

Q5 — Scholarship shortlisting

In [ ]:
totals = np.array([245,310,178,392,140,265,199,155,288,132])


ans1 = totals[totals>250]         #1
print(ans1)
print(ans1.size)


ans2 = totals[(totals>180) & (totals<250)]        #2
print(ans2)
print(ans2.size)


ans3 = totals[(totals<150) | (totals>380)]        #3
print(ans3)
print(ans3.size)


print(ans2.size)          #4


ans5 = totals[totals>200]             #5
print(ans5.mean())


print(np.where(totals<150)[0])        #6


print(totals[totals<=250].max())      #7

Q6 — After revaluation

In [5]:

marks = np.array([40, 55, 62, 88, 95, 33, 71, 58])


ans1 = np.round(marks*1.15,2)             #1
print(ans1)


ans2 = np.minimum(ans1,100)           #2
print(ans2)


ans3 = ans2-marks              #3
print(np.sum(ans3<10))


before = np.sum(marks<40)       #4
after = np.sum(ans2<40)
print(before,after)


topper = marks.max()         #5
print(np.round((marks/topper)*100,1))


ans6 = np.round(np.sum(ans2) - np.sum(marks), 2)          #6
print(ans6)
 

[ 46.    63.25  71.3  101.2  109.25  37.95  81.65  66.7 ]
[ 46.    63.25  71.3  100.   100.    37.95  81.65  66.7 ]
6
1 1
[ 42.1  57.9  65.3  92.6 100.   34.7  74.7  61.1]
64.85


Q7 — The result summary

In [ ]:
marks7 = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])
 
print(marks7.mean(), np.median(marks7))                          
print(marks7.max() - marks7.min())                                
print(marks7.argmax(), marks7.argmin())                            
print(np.sort(marks7)[-2])                                          
avg7 = marks7.mean()
print(np.sum(marks7 > avg7))                                        
std7 = marks7.std()
print(np.sum((marks7 >= avg7 - std7) & (marks7 <= avg7 + std7)))     
print(round((marks7.sum() - marks7.max()) / (len(marks7) - 1), 2))   

Q8 — Subject-wise and student-wise reports

In [ ]:
marks8 = np.array([[72, 85, 60, 91],
                    [45, 30, 98, 55],
                    [88, 66, 74, 100],
                    [95, 92, 55, 40],
                    [30, 48, 62, 70]])
 
print(marks8.mean(axis=0))                                    
print(marks8.sum(axis=1))
print(marks8.mean(axis=0).argmin())                             
print(marks8.sum(axis=1).argmax())                                
print(marks8.max(axis=0))                                          
print(np.sum(marks8 > 60, axis=0))                                   
print(marks8.std(axis=0).argmax())                                    
chem_col = marks8[:, 2]
lowest_chem_idx = chem_col.argmin()
print(marks8[lowest_chem_idx].sum())                                   
 

 Q9 — The annual function draw

In [ ]:
participants = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
 
np.random.seed(42)
print(np.random.choice(participants, 3, replace=False))         
 
np.random.seed(42)
attendance9 = np.random.randint(60, 101, 10)
print(attendance9)                                              
 
np.random.seed(42)
rand_table = np.random.rand(4, 3)
rand_marks = (rand_table * 100).astype(int)                      
print(rand_marks)
 
np.random.seed(42)
shuffled = participants.copy()
np.random.shuffle(shuffled)
print(shuffled[:4])                                                 
 
np.random.seed(42)
rolls9 = np.random.randint(1, 7, 20)
print(np.sum(rolls9 == 6))                                           
 
np.random.seed(42)
attendance9b = np.random.randint(60, 101, 10)
print(participants[attendance9b > 80])  

Q10 — Grace marks and weightage

In [ ]:
marks10 = np.array([[72, 85, 60, 91],
                     [45, 30, 98, 55],
                     [88, 66, 74, 100],
                     [95, 92, 55, 40]])
grace = np.array([5, 0, 8, 3])
weightage = np.array([1.2, 1.0, 1.1, 1.0])
 
graced = np.where(marks10 + grace > 100, 100, marks10 + grace)          
weighted = np.round(marks10 * weightage, 1)                              
diff10 = marks10 - marks10.mean(axis=0)                                   
print(diff10)
bonus = np.array([5, 0, 2, 0]).reshape(-1, 1)
marks10_bonus = marks10 + bonus                                             
print(marks10_bonus)
print(np.sum(diff10 < 0))                                                     
scaled10 = np.round((marks10 - marks10.mean(axis=0)) / marks10.std(axis=0), 2) 
print(scaled10)

Q11 — Distances and arrangements

In [ ]:
metres = np.array([200, 500, 900, 100, 700])
sanskrit = np.array([65, 70, 88, 92, 54])
 
dist = np.abs(metres.reshape(-1, 1) - metres)                            
print(dist)
print(dist.max(axis=1))                                                   
d0 = dist[0].astype(float).copy()
d0[0] = np.inf
print(d0.argmin())                                                          
 
temp11 = dist.astype(float).copy()
np.fill_diagonal(temp11, np.inf)
closest_pair = np.unravel_index(temp11.argmin(), temp11.shape)                
print(closest_pair)
 
rolls11 = np.arange(1, 25).reshape(-1, 6)                                       
print(rolls11)
 
col_method1 = sanskrit.reshape(-1, 1)                                             
col_method2 = sanskrit[:, np.newaxis]
print(col_method1)
print(col_method2)
 
row_form = sanskrit.reshape(1, -1)                                                 
print(row_form)
 

Q12 — The master mark sheet

In [ ]:
master = np.array([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])
 
flat_copy = master.flatten()                                                          
flat_copy[0] = 999
print(master)                                                                          
 
flat_view = master.ravel()                                                            
flat_view[-1] = 111
print(master)                                                                             
master[-1, -1] = 90 
 
mid_copy = master.copy()                                                                    
mid_copy[1] = 0
print(mid_copy)
print(master)                                                                               
 
first_two_double = master[:, :2] * 2                                                        
print(first_two_double)
print(master)
 
master[:, :2] *= 2                                                                              
print(master)
master = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
 
reduced = np.where(master > 50, master - 10, master)                                              
print(reduced)
print(master)                                                                                      
 

Q13 — Merging section records

In [ ]:
sec_A = np.array([[72, 85, 60],
                   [45, 30, 98],
                   [88, 66, 74]])
sec_B = np.array([[95, 92, 55],
                   [30, 48, 62]])
roll_C = np.array([201, 202, 203, 204])
marks_C = np.array([67, 82, 45, 91])
 
combined = np.vstack((sec_A, sec_B))                                                                  
print(combined.shape)
 
totals13 = combined.sum(axis=1)
table2 = np.hstack((combined, totals13.reshape(-1, 1)))                                               
print(table2)
 
table3 = np.hstack((roll_C.reshape(-1, 1), marks_C.reshape(-1, 1)))                                   
print(table3)
 
new_student = np.array([205, 73])
table4 = np.vstack((table3, new_student))                                                                  
print(table4)
 
serials = np.arange(1, combined.shape[0] + 1).reshape(-1, 1)
table5 = np.hstack((serials, combined))                                                                      
print(table5)
 
filtered13 = combined[totals13 > 200]                                                                           
print(filtered13)
 
grades13 = np.where(totals13 >= 225, 'A', np.where(totals13 >= 150, 'B', 'C'))
table7 = np.hstack((combined.astype(str), grades13.reshape(-1, 1)))                                               
print(table7)
 

Q14 — Cleaning and grading

In [ ]:
marks14 = np.array([[70, 65, 80],
                     [55, 90, 32],
                     [88, 76, 91],
                     [40, 52, 45],
                     [60, 58, 66]])
attendance14 = np.array([88, -1, 105, 76, 45, -1, 92, 120, 67, 30])
 
capped14 = np.where(attendance14 > 100, 100, attendance14)
valid_mask = capped14 != -1
avg14 = capped14[valid_mask].mean()
repaired = np.where(capped14 == -1, avg14, capped14)                                                              
print(repaired)
 
labels14 = np.where(repaired >= 85, 'Regular', np.where(repaired >= 60, 'Average', 'Short'))                        
print(labels14)
 
short_idx = np.where(labels14 == 'Short')[0]                                                                          
print(short_idx, repaired[short_idx])
 
rows14, cols14 = np.where(marks14 < 50)                                                                                 
print("rows:", rows14)
print("cols:", cols14)
 
print(marks14[rows14, cols14])                                                                                          
 
below35_count = np.sum(marks14 < 35)
marks14_fixed = np.where(marks14 < 35, 35, marks14)                                                                        
print(below35_count)
 
below60_per_student = np.sum(marks14 < 60, axis=1)
print(below60_per_student.argmax())                                                                                         
 

Q15 — The final weighted result

In [ ]:
M = np.array([[70, 65, 80],
              [55, 90, 72],
              [88, 76, 91],
              [60, 58, 66]])
w = np.array([0.3, 0.3, 0.4])
W = np.array([[0.3, 0.5],
              [0.3, 0.2],
              [0.4, 0.3]])
 
final15 = M @ w                                                                                                                # 1
print(np.round(final15, 2))
print(final15.argmax())                                                                                                          # 2
 
subject_totals = np.ones(M.shape[0]) @ M                                                                                            # 3 -> matches expected
print(subject_totals)
 
final2 = M @ W                                                                                                                         # 4 -> matches expected
print(np.round(final2, 2))
 
print(np.sum(final2[:, 1] > final2[:, 0]))                                                                                                # 5
 
diff15 = np.round(final2[:, 1] - final2[:, 0], 2)                                                                                           # 6 -> matches expected
print(diff15)
 
better = np.max(final2, axis=1)
result15 = np.hstack((M, better.reshape(-1, 1)))                                                                                              # 7
print(result15)