Q1. Create an array of the first 12 odd numbers using a single np.arange call.

In [2]:
import numpy as np

In [9]:
x = np.arange(1,24,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


Q2. Using np.linspace, create 9 equally spaced values from 5 to 45. Before running, predict the gap
between consecutive values - then verify.

In [ ]:
x = np.linspace(5,45,9)
print(x)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


Q3. Create np.arange(1, 10) and np.linspace(1, 9, 9). Print both and compare their dtype. Why are
they different?

In [12]:
x = np.arange(1,10)
y = np.linspace(1,9,9)
print(x)
print(y)
print(x.dtype)
print(y.dtype)

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
int64
float64


The dtype is different becuase arange gives integer value whereas linspace gives float value

Q4. Create a 6x6 identity matrix with integer dtype - the output must show no decimal points.

In [16]:
x = np.eye(6, dtype=int)
print(x)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


Q5. Create a 3x4 matrix where every element is 5, and report its shape, size, and ndim

In [18]:
x = np.full((3,4),5)
print(x.shape)
print(x.size)
print(x.ndim)

(3, 4)
12
2


Q6. Given a = np.array([2, 4, 6]) and b = np.array([2.0, 4.0, 6.0]) - check both dtypes, then convert b
to int with astype and verify the dtypes now match.

In [21]:
a = np.array([2,4,6])
b = np.array([2.0, 4,0, 6,0])
print(a.dtype)
print(b.dtype)
c = b.astype(int)
print(a.dtype)
print(c.dtype)


int64
float64
int64
int64


Q7. Predict the exact output of np.array([10.9, 25.5, 39.99]).astype(int) before running it. What rule
does the result prove?

In [22]:
x = np.array([10.0,25.5,39.99])
print(x.astype(int))

[10 25 39]


It converts float into integer

Q8. Given arr = np.arange(10, 101, 10) - extract: (a) the 4th element, (b) the last element using
negative indexing, (c) the 2nd-last element.

In [27]:
arr = np.arange(10, 101, 10)
print(arr)
print(arr[3])
print(arr[-1])
print(arr[-2])

[ 10  20  30  40  50  60  70  80  90 100]
40
100
90


Q9. From the same arr, slice out exactly [30 40 50 60], and separately produce the full array in
reverse.

In [31]:
arr = np.arange(10,101,10)
print(arr[2:6])
print(arr[::-1])

[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


Q10. Given arr = np.arange(1, 21) - extract every 3rd element starting from index 1 (result: 2, 5, 8,
...)


In [34]:
arr = np.arange(1,21)
print(arr[1::3])

[ 2  5  8 11 14 17 20]


Q11. Using one slice only, extract everything from arr (1-20) EXCEPT the first two and the last two
elements

In [37]:
arr = np.arange(1,21)
print(arr[2:18])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


Q12. Using the matrix below, extract: (a) the 3rd row, (b) the last column, (c) the centre 3x3 block
m = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

In [48]:
m = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])
print(m[2])
print(m[:,4])
print(m[1:4, 1:4])


[11 12 13 14 15]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Q13. From the same matrix, extract the four corner elements as a 2x2 array - using step slicing
only

In [49]:
print(m[::4, ::4])

[[ 1  5]
 [21 25]]


Q14. From the same matrix, extract every alternate row AND every alternate column at the same
time (the result is 3x3)

In [50]:
print(m[::2,::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
